### ISSUE TITLE
Login/Connect to Spotify

### ISSUE THREAD

**Issue by hannaco** [hannaco/SpotiFry#1]
## Epic
Create a page where the user can login to their Spotify account

## User Stories
As a user, I want to be able to connect my Spotify account so that I can personalize my recommendations

## Tasks
- [x] Initial page design
- [x] Implementation of UI
- [x] API call to connect account
- [x] #9
- [x] Connect backend to frontend

**Comment by bulaienTang** [comment]
Finished.
