### ISSUE TITLE
Command Line Script

### ISSUE THREAD

**Issue by hannaco** [hannaco/SpotiFry#2]
## Epic
Create a command line script in Python that creates a playlist when manually passed parameters

## User Stories
As a user, I want to be able to create a customized playlist using a CLI interface

## Tasks
- [x] Create skeleton Python Script, accept arguments and authenticate user
- [x] Test functionality to create playlist, passing various combinations of parameters
- [x] Write playlist information to database when script runs

**Comment by josephpinto** [comment]
We have successfully enabled the functionality of playlists being created, but are yet to roll out a production version that accepts custom parameters. We have experimented with methods to achieve this and it should be very doable early within the next sprint.
