### ISSUE TITLE
Integrate Frontend and Backend

### ISSUE THREAD

**Issue by hannaco** [hannaco/SpotiFry#4]
## Epic
Connect the frontend and backend to create a functional webapp

## Tasks

- [x] pass data from backend server to React client
- [x] pass data to server from React client
- [x] successfully create and return a playlist ID by passing token from frontend

**Comment by bulaienTang** [comment]
Are we marking this issue as completed, since ll the Tasks are checked?
