### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by hannaco** [hannaco/SpotiFry#5]
## Epic
Create a splash page of user's top songs, where they can quickly create a customized playlist.

## User Stories
As a user, I want to be able to quickly create a playlist based on my top songs

## Tasks
- [x] Initial page design
- [x] Implementation of UI
- [x] Skeleton function calls

**Comment by bulaienTang** [comment]
TODO: list the users' top artists on the splash page

**Comment by bulaienTang** [comment]
removed functionality
